# -*- coding: utf-8 -*-

# languages.py

LANGUAGES = {
    'portugues': {
        # Títulos de Janelas e Abas
        'app_title': 'GERENCIAMentor',
        'main_menu_title': 'Menu Principal - Sistema de Produção',
        'stop_tracking_window_title': 'Apontamento de Parada em Tempo Real',
        'config_win_title': 'Configurações do Banco de Dados',
        'manager_title': 'Gerenciador de Tabelas de Apoio',
        'edit_order_title': 'Editar Ordem de Produção - WO: {wo}',
        'confirm_cancel_order_title': 'Confirmar Cancelamento',
        'view_appointments_title': 'Visualizar Apontamentos',
        'stop_times_window_title': 'Apontamento de Paradas',
        'confirm_delete_appointment_title': 'Confirmar Exclusão de Apontamento',
        'edit_appointment_title': 'Editar Apontamento - ID: {id}',
        'stop_details_for_appointment': 'Detalhes das Paradas para Apontamento ID: {id}',
        'service_manager_title': 'Gerenciador de Etapas - WO: {wo}',
        'add_service_title': 'Adicionar Nova Etapa',
        'edit_service_title': 'Editar Etapa',
        'manager_dashboard_title': 'Dashboard Gerencial',
        'pcp_report_title': 'Relatório de Produção (PCP)',
        'wo_details_title': 'Detalhes da Ordem de Produção',

        # Botões
        'btn_production_entry': 'Apontamento de Produção',
        'btn_pcp_management': 'Gerenciamento PCP',
        'btn_view_entries': 'Visualizar Apontamentos',
        'btn_manage_tables': 'Gerenciar Tabelas de Apoio',
        'start_production_btn': 'Iniciar Produção',
        'finish_production_btn': 'Finalizar Produção',
        'register_entry_btn': 'Registar Apontamento Final',
        'finish_stop_btn': 'Finalizar Parada',
        'test_connection_btn': 'Testar Conexão',
        'save_btn': 'Salvar',
        'cancel_btn': 'Cancelar',
        'save_changes_btn': 'Salvar Alterações',
        'edit_order_btn': 'Alterar Ordem Selecionada',
        'cancel_order_btn': 'Cancelar Ordem Selecionada',
        'add_new_btn': 'Adicionar Novo',
        'edit_selected_btn': 'Editar Selecionado',
        'delete_selected_btn': 'Excluir Selecionado',
        'apply_filters_btn': 'Aplicar Filtros',
        'clear_filters_btn': 'Limpar Filtros',
        'export_csv_btn': 'Exportar para CSV',
        'open_stop_times_btn': 'Configurar Paradas',
        'generate_fields_btn': 'Gerar Campos',
        'view_stop_details_btn': 'Ver Detalhes das Paradas',
        'edit_appointment_btn': 'Editar Apontamento',
        'delete_appointment_btn': 'Excluir Apontamento',
        'btn_manage_services': 'Gerenciar Etapas',
        'add_service_btn': 'Adicionar Etapa',
        'edit_service_btn': 'Editar Etapa',
        'delete_service_btn': 'Excluir Etapa',
        'add_machine_btn': 'Adicionar Máquina à Lista',
        'remove_selected_btn': 'Remover Selecionada',
        'move_up_btn': 'Subir na Fila',
        'move_down_btn': 'Descer na Fila',
        'view_report_btn': 'Ver Relatório',
        'export_xlsx_btn': 'Exportar para XLSX',
        'export_pdf_btn': 'Exportar para PDF',

        # Labels e Textos de Interface
        'production_status_running': 'EM PRODUÇÃO',
        'production_status_stopped': 'PARADO',
        'production_status_idle': 'AGUARDANDO INÍCIO',
        'elapsed_time_label': 'Tempo Decorrido:',
        'stop_reason_label': 'Motivo da Parada:',
        'stop_time_label': 'Tempo de Parada:',
        'host_label': 'Host',
        'port_label': 'Porta',
        'user_label': 'Usuário',
        'password_label': 'Senha',
        'db_label': 'Banco',
        'table_label': 'Tabela de Apontamentos',
        'language_label': 'Idioma',
        'equipment_label': 'Equipamento de Trabalho',
        'printer_label': 'Printer Operator',
        'shift_label': 'Shift',
        'date_start_label': 'Data Início',
        'date_end_label': 'Data Fim',
        'has_stops_question': 'Possui Paradas?',
        'num_stops_label': 'Número de Paradas',
        'stop_label': 'Parada',
        'other_motives_label': 'Especifique o Motivo',
        'has_stops_question_short': 'Paradas?',
        'yes_short': 'Sim',
        'no_short': 'Não',
        'service_select_label': 'Selecionar Etapa/Serviço:',
        'col_tempo_por_folha': 'Tempo por Folha (ms)',
        'service_on_machine_queue_label': 'Serviço na Fila da Máquina:',
        'order_status_label': 'Status Ordem:',
        'wo_tracking_label': 'Acompanhamento da WO:',

        # Seções de Tela (LabelFrame)
        'form_data_section': 'Dados',
        'filter_section': 'Filtros de Apontamentos',
        'manager_select_table': 'Seleção de Tabela',
        'stop_times_control_section': 'Controle de Paradas',
        'new_order_section': "Nova Ordem de Produção",
        'created_orders_section': "Ordens de Produção Criadas",
        'services_section_title': 'Etapas da Ordem',
        'order_info_section': 'Informações da Ordem',
        'stops_history_section': 'Histórico de Paradas',
        'machine_details_section': 'Detalhes de Produção por Máquina',
        'kpi_history_section': 'Indicadores Chave (do Histórico de Produção)',
        'history_actions_section': 'Ações do Histórico',
        'production_history_tab': 'Histórico de Produção',
        'pending_orders_tab': 'Ordens Pendentes',

        # KPIs
        'kpi_total_produced': 'Qtd. Total Produzida',
        'kpi_total_production_time': 'Tempo Total de Produção',
        'kpi_total_stop_time': 'Tempo Total de Parada',
        'kpi_total_waste': 'Total de Perdas (Prod.)',


        # Colunas de Tabelas
        'col_id': 'ID', 'col_descricao': 'Descrição', 'col_nome': 'Nome', 'col_codigo': 'Código',
        'col_valor': 'Valor', 'col_data': 'Data', 'col_horainicio': 'Hora Início', 'col_horafim': 'Hora Fim',
        'col_wo': 'WO', 'col_cliente': 'Client', 'col_qtde_cores': 'COLORS QTY',
        'col_tipo_papel': 'PAPER TYPE', 'col_numeroinspecao': 'Inspection Number', 'col_gramatura': 'Gramatura',
        'col_formato': 'Formato', 'col_fsc': 'FSC', 'col_tiragem_em_folhas': 'Sheet Run',
        'col_giros_rodados': 'Revolutions', 'col_perdas_malas': 'Setup Sheets', 'col_total_lavagens': 'Total Washes',
        'col_total_acertos': 'Total Acertos', 'col_ocorrencias': 'Ocorrências',
        'col_motivos_parada': 'Motivo da Parada', 'col_quantidadeproduzida': 'Quantity Produced',
        'col_status': 'Status', 'col_data_criacao': 'Data Criação', 'col_duracao': 'Duração',
        'col_impressor': 'Impressor', 'col_turno': 'Turno', 'col_data_previsao': 'Data Previsão',
        'col_data_cadastro': 'Data Cadastro', 'col_servico_descricao': 'Descrição da Etapa',
        'col_servico_status': 'Status da Etapa', 'col_sequencia': 'Sequência',
        'col_perdas_producao': 'Waste (Production)',
        'col_motivo_perda': 'Waste Reason',
        'Acabamento': 'Acabamento',
        'giros_previstos': 'Planned Revolutions',
        'col_acabamento': 'Acabamento',
        'tempo_previsto': 'Planned Time',
        'col_type': 'Tipo',
        'col_reason': 'Motivo',
        'col_start': 'Início',
        'col_end': 'Fim',
        'col_progress': 'Progresso da Produção',
        'col_delay_status': 'Status Atraso',
        'col_service_machine': 'Serviço/Máquina',
        'col_paper': 'Papel',
        'col_colors': 'Cores',
        'col_target_run': 'Tiragem Meta',
        'col_operator': 'Operador',
        'col_prod_start': 'Início Prod.',
        'col_prod_end': 'Fim Prod.',
        'col_perdas': 'Waste (Setup)',


        # Menus
        'menu_settings': 'Configurações',
        'menu_db_config': 'Configurar Banco de Dados',
        'menu_manage': 'Gerenciar',
        'menu_manage_lookup': 'Gerenciar Tabelas de Apoio',
        'menu_view_appointments': 'Visualizar Apontamentos',
        'menu_manage_pcp': 'Gerenciar Ordens (PCP)',

        # Mensagens de Sucesso
        'cancel_order_success': 'Ordem de Produção cancelada com sucesso!',
        'update_order_success': 'Ordem de Produção atualizada com sucesso!',
        'loaded_appointments_success': 'Dados da tabela "{table_name}" carregados com sucesso!',
        'export_success_message': 'Dados exportados com sucesso para:\n{path}',
        'stop_times_saved_success': 'Dados de paradas salvos com sucesso!',
        'delete_appointment_success': 'Apontamento ID {id} excluído com sucesso!',
        'update_success': 'Apontamento ID {id} atualizado com sucesso!',
        'entry_edited_success': 'Entrada atualizada com sucesso!',
        'new_entry_added_success': 'Nova entrada adicionada com sucesso!',
        'delete_success': 'Entrada excluída com sucesso!',
        'config_save_success': 'Configuração salva com sucesso. Pode ser necessário reiniciar a aplicação.',
        'test_connection_success': 'Conexão com o banco de dados bem-sucedida!',
        'order_save_success': 'Ordem de produção salva com sucesso!',
        'service_saved_success': 'Etapa salva com sucesso!',
        'service_deleted_success': 'Etapa excluída com sucesso!',
        'production_saved_success': 'Apontamento de produção registrado com sucesso!',

        # Mensagens de Erro e Alerta
        'cancel_order_failed': 'Falha ao cancelar a Ordem de Produção: {error}',
        'update_order_failed': 'Falha ao atualizar a Ordem de Produção: {error}',
        'selection_required_title': 'Seleção Necessária',
        'select_order_to_edit_msg': 'Por favor, selecione uma ordem para alterar.',
        'select_order_to_cancel_msg': 'Por favor, selecione uma ordem para cancelar.',
        'invalid_status_for_action_msg': 'Ação não permitida! Apenas ordens com status "Em Aberto" podem ser alteradas ou canceladas.',
        'no_data_to_export': 'Não há dados para exportar.',
        'export_error': 'Erro ao exportar dados para CSV: {error}',
        'db_load_appointments_failed': 'Falha ao carregar apontamentos da tabela "{table_name}": {error}',
        'invalid_num_stops_error': 'Por favor, insira um número válido para a quantidade de paradas.',
        'validation_error_invalid_selection': 'Por favor, selecione um item válido.',
        'validation_error_time_order': 'Hora Fim deve ser posterior à Hora Início.',
        'validation_error_fix_fields_stops': 'Por favor, corrija os campos de parada destacados em vermelho.',
        'select_appointment_to_view_stops': 'Por favor, selecione um apontamento para ver os detalhes das paradas.',
        'no_stops_for_appointment': 'Este apontamento não possui paradas registradas.',
        'no_stops_for_appointment_full': 'Nenhuma parada registrada para este apontamento.',
        'db_load_stops_failed': 'Falha ao carregar detalhes das paradas: {error}',
        'db_conn_incomplete': 'Configuração do banco de dados incompleta ou ausente.',
        'invalid_input': 'Entrada Inválida',
        'filter_date_format_warning': 'Formato de data inválido para o campo "{field}". Use DD/MM/AAAA.',
        'delete_appointment_failed': 'Falha ao excluir apontamento: {error}',
        'select_appointment_to_edit': 'Selecione um apontamento para editar.',
        'select_appointment_to_delete': 'Selecione um apontamento para excluir.',
        'update_failed': 'Falha ao atualizar o apontamento: {error}',
        'select_table_warning': 'Por favor, selecione uma tabela para continuar.',
        'schema_not_found': 'Esquema para a tabela "{table_name}" não encontrado.',
        'db_load_table_failed': 'Falha ao carregar dados da tabela "{display_name}": {error}',
        'select_entry_to_edit': 'Por favor, selecione uma entrada para editar.',
        'save_entry_validation_error': 'Erro de validação para o campo "{field_name}". Insira um número inteiro válido.',
        'db_save_failed': 'Falha ao salvar no banco de dados. Erro: {error}',
        'db_delete_failed': 'Falha ao excluir do banco de dados. Erro: {error}',
        'config_save_error': 'Falha ao salvar o arquivo de configuração: {error}',
        'test_connection_warning_fill_fields': 'Por favor, preencha todos os campos de conexão para testar.',
        'test_connection_failed_db': 'Falha na conexão com o banco de dados: {error}',
        'required_field_warning': 'O campo "{field_name}" é obrigatório.',
        'integrity_error_wo': "A WO '{wo}' já existe.",
        'save_order_error': 'Não foi possível salvar a ordem. Verifique se os dados estão corretos.\nDetalhes: {error}',
        'empty_data_warning': "Nenhum dado para salvar.",
        'generic_load_error': 'Falha ao carregar dados: {error}',
        'service_save_failed': 'Falha ao salvar a etapa: {error}',
        'service_delete_failed': 'Falha ao excluir a etapa: {error}',
        'no_pending_services': 'Nenhuma etapa pendente para esta WO.',
        'select_wo_first': 'Selecione uma WO para ver as etapas.',
        'select_service_to_edit': 'Selecione uma etapa para editar.',
        'select_service_to_delete': 'Selecione uma etapa para excluir.',
        'production_save_failed': 'Falha ao salvar o apontamento de produção: {error}',
        'final_appointment_validation_error': 'Os campos "Giros Rodados" e "Quantidade Produzida" são obrigatórios.',

        
        # Mensagens de Confirmação
        'confirm_cancel_order_msg': 'Tem certeza que deseja cancelar permanentemente a ordem com WO "{wo}"? Esta ação não pode ser desfeita.',
        'confirm_delete_appointment_msg': 'Tem certeza que deseja excluir permanentemente o apontamento com ID {id}? Todas as paradas associadas também serão excluídas. Esta ação não pode ser desfeita.',
        'confirm_delete_title': 'Confirmar Exclusão',
        'confirm_delete_message': 'Tem certeza que deseja excluir permanentemente a entrada com ID "{pk_value}" da tabela "{display_name}"?',
        'confirm_delete_service_msg': 'Tem certeza que deseja excluir a etapa "{desc}"?',

        # Outros
        'csv_files_type': 'Arquivos CSV',
        'all_files_type': 'Todos os Arquivos',
        'save_csv_dialog_title': 'Salvar como CSV',

        'initial_selection_section': '1. Seleção Inicial',
        'setup_section': '2. Setup Entry',
        'production_section': '3. Production Entry',
        'start_setup_btn': 'Start Setup',
        'finish_setup_btn': 'Finalizar Setup',
        'point_setup_stop_btn': 'Apontar Parada de Setup',
        'point_prod_stop_btn': 'Apontar Parada de Produção',
        'status_idle': 'AGUARDANDO',
        'status_setup_running': 'SETUP EM ANDAMENTO',
        'status_setup_done': 'SETUP FINALIZADO',
        'status_prod_running': 'PRODUÇÃO EM ANDAMENTO',
        'setup_fields_required': 'Todos os campos de Setup (Perdas, Malas, Lavagens, Nº Inspeção) devem ser preenchidos para finalizar.',
        'setup_saved_success': 'Dados de Setup salvos com sucesso! Prossiga para a produção.',
        'setup_save_failed': 'Falha ao salvar os dados de Setup: {error}',
        'status_prod_done': 'PRODUÇÃO FINALIZADA',
        'finished': 'CONCLUÍDO',
    },
    'english': {
        # Window and Tab Titles
        'app_title': 'GERENCIAMentor',
        'main_menu_title': 'Main Menu - Production System',
        'stop_tracking_window_title': 'Real-Time Stop Tracking',
        'config_win_title': 'Database Settings',
        'manager_title': 'Lookup Table Manager',
        'edit_order_title': 'Edit Production Order - WO: {wo}',
        'confirm_cancel_order_title': 'Confirm Cancellation',
        'view_appointments_title': 'View Entries',
        'stop_times_window_title': 'Stop Time Entry',
        'confirm_delete_appointment_title': 'Confirm Entry Deletion',
        'edit_appointment_title': 'Edit Entry - ID: {id}',
        'stop_details_for_appointment': 'Stop Details for Entry ID: {id}',
        'service_manager_title': 'Step Manager - WO: {wo}',
        'add_service_title': 'Add New Step',
        'edit_service_title': 'Edit Step',
        'manager_dashboard_title': 'Manager Dashboard',
        'pcp_report_title': 'Production Report (PCP)',
        'wo_details_title': 'Work Order Details',

        # Buttons
        'btn_production_entry': 'Production Entry',
        'btn_pcp_management': 'PCP Management',
        'btn_view_entries': 'View Entries',
        'btn_manage_tables': 'Manage Lookup Tables',
        'start_production_btn': 'Start Production',
        'finish_production_btn': 'Finish Production',
        'register_entry_btn': 'Register Final Entry',
        'finish_stop_btn': 'Finish Stop',
        'test_connection_btn': 'Test Connection',
        'save_btn': 'Save',
        'cancel_btn': 'Cancel',
        'save_changes_btn': 'Save Changes',
        'edit_order_btn': 'Edit Selected Order',
        'cancel_order_btn': 'Cancel Selected Order',
        'add_new_btn': 'Add New',
        'edit_selected_btn': 'Edit Selected',
        'delete_selected_btn': 'Delete Selected',
        'apply_filters_btn': 'Apply Filters',
        'clear_filters_btn': 'Clear Filters',
        'export_csv_btn': 'Export to CSV',
        'open_stop_times_btn': 'Configure Stops',
        'generate_fields_btn': 'Generate Fields',
        'view_stop_details_btn': 'View Stop Details',
        'edit_appointment_btn': 'Edit Entry',
        'delete_appointment_btn': 'Delete Entry',
        'btn_manage_services': 'Manage Steps',
        'add_service_btn': 'Add Step',
        'edit_service_btn': 'Edit Step',
        'delete_service_btn': 'Delete Step',
        'add_machine_btn': 'Add Machine to List',
        'remove_selected_btn': 'Remove Selected',
        'move_up_btn': 'Move Up',
        'move_down_btn': 'Move Down',
        'view_report_btn': 'View Report',
        'export_xlsx_btn': 'Export to XLSX',
        'export_pdf_btn': 'Export to PDF',


        # Labels and UI Text
        'production_status_running': 'IN PRODUCTION',
        'production_status_stopped': 'STOPPED',
        'production_status_idle': 'WAITING FOR START',
        'elapsed_time_label': 'Elapsed Time:',
        'stop_reason_label': 'Stop Reason:',
        'stop_time_label': 'Stop Time:',
        'host_label': 'Host',
        'port_label': 'Port',
        'user_label': 'User',
        'password_label': 'Password',
        'db_label': 'Database',
        'table_label': 'Entries Table',
        'language_label': 'Language',
        'equipment_label': 'Work Equipment',
        'printer_label': 'Printer Operator',
        'shift_label': 'Shift',
        'date_start_label': 'Start Date',
        'date_end_label': 'End Date',
        'has_stops_question': 'Are there stops?',
        'num_stops_label': 'Number of Stops',
        'stop_label': 'Stop',
        'other_motives_label': 'Specify Reason',
        'has_stops_question_short': 'Stops?',
        'yes_short': 'Yes',
        'no_short': 'No',
        'service_select_label': 'Select Step/Service:',
        'service_on_machine_queue_label': 'Service in Machine Queue:',
        'order_status_label': 'Order Status:',
        'wo_tracking_label': 'WO Tracking:',

        # Screen Sections (LabelFrame)
        'form_data_section': 'Data',
        'filter_section': 'Entry Filters',
        'manager_select_table': 'Table Selection',
        'stop_times_control_section': 'Stop Control',
        'new_order_section': "New Production Order",
        'created_orders_section': "Created Production Orders",
        'services_section_title': 'Order Steps',
        'order_info_section': 'Order Information',
        'stops_history_section': 'Stops History',
        'machine_details_section': 'Production Details per Machine',
        'kpi_history_section': 'Key Indicators (from Production History)',
        'history_actions_section': 'History Actions',
        'production_history_tab': 'Production History',
        'pending_orders_tab': 'Pending Orders',

        # KPIs
        'kpi_total_produced': 'Total Qty. Produced',
        'kpi_total_production_time': 'Total Production Time',
        'kpi_total_stop_time': 'Total Stop Time',
        'kpi_total_waste': 'Total Waste (Prod.)',

        # Table Columns
        'col_id': 'ID', 'col_descricao': 'Description', 'col_nome': 'Name', 'col_codigo': 'Code',
        'col_valor': 'Value', 'col_data': 'Date', 'col_horainicio': 'Start Time', 'col_horafim': 'End Time',
        'col_wo': 'WO', 'col_cliente': 'Client', 'col_qtde_cores': 'COLORS QTY',
        'col_tipo_papel': 'PAPER TYPE', 'col_numeroinspecao': 'Inspection Number', 'col_gramatura': 'Grammage',
        'col_formato': 'Format', 'col_fsc': 'FSC', 'col_tiragem_em_folhas': 'Sheet Run',
        'col_giros_rodados': 'Revolutions', 'col_perdas_malas': 'Setup Sheets', 'col_total_lavagens': 'Total Washes',
        'col_total_acertos': 'Total Adjustments', 'col_ocorrencias': 'Occurrences',
        'col_motivos_parada': 'Stop Reason', 'col_quantidadeproduzida': 'Quantity Produced',
        'col_status': 'Status', 'col_data_criacao': 'Creation Date', 'col_duracao': 'Duration',
        'col_impressor': 'Printer Operator', 'col_turno': 'Shift', 'col_data_previsao': 'Forecast Date',
        'col_data_cadastro': 'Registration Date', 
        'col_servico_descricao': 'Step Description',
        'col_servico_status': 'Step Status', 'col_sequencia': 'Sequence',
        'col_perdas_producao': 'Waste (Production)',
        'col_motivo_perda': 'Waste Reason',
        'Acabamento': 'Finishing',
        'giros_previstos': 'Planned Revolutions',
        'col_acabamento': 'Finishing',
        'tempo_previsto': 'Planned Time',
        'col_type': 'Type',
        'col_reason': 'Reason',
        'col_start': 'Start',
        'col_end': 'End',
        'col_progress': 'Production Progress',
        'col_delay_status': 'Delay Status',
        'col_service_machine': 'Service/Machine',
        'col_paper': 'Paper',
        'col_colors': 'Colors',
        'col_target_run': 'Target Run',
        'col_operator': 'Operator',
        'col_prod_start': 'Prod. Start',
        'col_prod_end': 'Prod. End',
        'col_perdas': 'Waste (Setup)',

        # Menus
        'menu_settings': 'Settings',
        'menu_db_config': 'Configure Database',
        'menu_manage': 'Manage',
        'menu_manage_lookup': 'Manage Lookup Tables',
        'menu_view_appointments': 'View Entries',
        'menu_manage_pcp': 'Manage Orders (PCP)',

        # Success Messages
        'cancel_order_success': 'Production Order cancelled successfully!',
        'update_order_success': 'Production Order updated successfully!',
        'loaded_appointments_success': 'Data from table "{table_name}" loaded successfully!',
        'export_success_message': 'Data exported successfully to:\n{path}',
        'stop_times_saved_success': 'Stop data saved successfully!',
        'delete_appointment_success': 'Entry ID {id} deleted successfully!',
        'update_success': 'Entry ID {id} updated successfully!',
        'entry_edited_success': 'Entry updated successfully!',
        'new_entry_added_success': 'New entry added successfully!',
        'delete_success': 'Entry deleted successfully!',
        'config_save_success': 'Configuration saved successfully. You may need to restart the application.',
        'test_connection_success': 'Database connection successful!',
        'order_save_success': 'Production order saved successfully!',
        'service_saved_success': 'Step saved successfully!',
        'service_deleted_success': 'Step deleted successfully!',
        'production_saved_success': 'Production entry registered successfully!',

        # Error and Warning Messages
        'cancel_order_failed': 'Failed to cancel Production Order: {error}',
        'update_order_failed': 'Failed to update Production Order: {error}',
        'selection_required_title': 'Selection Required',
        'select_order_to_edit_msg': 'Please select an order to edit.',
        'select_order_to_cancel_msg': 'Please select an order to cancel.',
        'invalid_status_for_action_msg': 'Action not allowed! Only orders with "Open" status can be edited or cancelled.',
        'no_data_to_export': 'No data to export.',
        'export_error': 'Error exporting data to CSV: {error}',
        'db_load_appointments_failed': 'Failed to load entries from table "{table_name}": {error}',
        'invalid_num_stops_error': 'Please enter a valid number for the quantity of stops.',
        'validation_error_invalid_selection': 'Please select a valid item.',
        'validation_error_time_order': 'End Time must be after Start Time.',
        'validation_error_fix_fields_stops': 'Please correct the stop fields highlighted in red.',
        'select_appointment_to_view_stops': 'Please select an entry to view stop details.',
        'no_stops_for_appointment': 'This entry has no registered stops.',
        'no_stops_for_appointment_full': 'No stops registered for this entry.',
        'db_load_stops_failed': 'Failed to load stop details: {error}',
        'db_conn_incomplete': 'Database configuration is incomplete or missing.',
        'invalid_input': 'Invalid Input',
        'filter_date_format_warning': 'Invalid date format for field "{field}". Use YYYY-MM-DD.',
        'delete_appointment_failed': 'Failed to delete entry: {error}',
        'select_appointment_to_edit': 'Select an entry to edit.',
        'select_appointment_to_delete': 'Select an entry to delete.',
        'update_failed': 'Failed to update entry: {error}',
        'select_table_warning': 'Please select a table to continue.',
        'schema_not_found': 'Schema for table "{table_name}" not found.',
        'db_load_table_failed': 'Failed to load data from table "{display_name}": {error}',
        'select_entry_to_edit': 'Please select an entry to edit.',
        'save_entry_validation_error': 'Validation error for field "{field_name}". Please enter a valid integer.',
        'db_save_failed': 'Failed to save to database. Error: {error}',
        'db_delete_failed': 'Failed to delete from database. Error: {error}',
        'config_save_error': 'Failed to save configuration file: {error}',
        'test_connection_warning_fill_fields': 'Please fill all connection fields to test.',
        'test_connection_failed_db': 'Database connection failed: {error}',
        'required_field_warning': 'The field "{field_name}" is required.',
        'integrity_error_wo': "The WO '{wo}' already exists.",
        'save_order_error': 'Could not save the order. Please check if the data is correct.\nDetails: {error}',
        'empty_data_warning': "No data to save.",
        'generic_load_error': 'Failed to load data: {error}',
        'service_save_failed': 'Failed to save the step: {error}',
        'service_delete_failed': 'Failed to delete the step: {error}',
        'no_pending_services': 'No pending steps for this WO.',
        'select_wo_first': 'Select a WO to see the steps.',
        'select_service_to_edit': 'Select a step to edit.',
        'select_service_to_delete': 'Select a step to delete.',
        'production_save_failed': 'Failed to save production entry: {error}',
        'final_appointment_validation_error': 'The "Revolutions" and "Quantity Produced" fields are required.',

        # Confirmation Messages
        'confirm_cancel_order_msg': 'Are you sure you want to permanently cancel the order with WO "{wo}"? This action cannot be undone.',
        'confirm_delete_appointment_msg': 'Are you sure you want to permanently delete the entry with ID {id}? All associated stops will also be deleted. This action cannot be undone.',
        'confirm_delete_title': 'Confirm Deletion',
        'confirm_delete_message': 'Are you sure you want to permanently delete the entry with ID "{pk_value}" from the "{display_name}" table?',
        'confirm_delete_service_msg': 'Are you sure you want to delete the step "{desc}"?',

        # Others
        'csv_files_type': 'CSV Files',
        'all_files_type': 'All Files',
        'save_csv_dialog_title': 'Save as CSV',

        'initial_selection_section': '1. Initial Selection',
        'setup_section': '2. Setup Entry',
        'production_section': '3. Production Entry',
        'start_setup_btn': 'Start Setup',
        'finish_setup_btn': 'Finish Setup',
        'point_setup_stop_btn': 'Log Setup Stop',
        'point_prod_stop_btn': 'Log Production Stop',
        'status_idle': 'IDLE',
        'status_setup_running': 'SETUP IN PROGRESS',
        'status_setup_done': 'SETUP FINISHED',
        'status_prod_running': 'PRODUCTION IN PROGRESS',
        'setup_fields_required': 'All Setup fields (Waste, Setup Sheets, Washes, Inspection No.) must be filled to finish.',
        'setup_saved_success': 'Setup data saved successfully! Proceed to production.',
        'setup_save_failed': 'Failed to save Setup data: {error}',
        'status_prod_done': 'PRODUCTION FINISHED',
        'finished': 'COMPLETED',
        'col_tempo_por_folha': 'Time per Sheet (ms)',
    },
}