# -*- coding: utf-8 -*-

# schemas.py

LOOKUP_TABLE_SCHEMAS = {
    "qtde_cores_tipos": {"display_name_key": "col_qtde_cores", "table": "qtde_cores_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}, "giros": {"type": "int", "db_column": "giros", "display_key": "col_giros_rodados", "editable": True}}},
    "tipos_papel": {"display_name_key": "col_tipo_papel", "table": "tipos_papel", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "impressores": {"display_name_key": "printer_label", "table": "impressores", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "nome": {"type": "str", "db_column": "nome", "display_key": "col_nome", "editable": True}}},
    "motivos_parada_tipos": {"display_name_key": "col_motivos_parada", "table": "motivos_parada_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "codigo": {"type": "int", "db_column": "codigo", "display_key": "col_codigo", "editable": True}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "motivos_perda_tipos": {"display_name_key": "col_motivo_perda", "table": "motivos_perda_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "formatos_tipos": {"display_name_key": "col_formato", "table": "formatos_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "gramaturas_tipos": {"display_name_key": "col_gramatura", "table": "gramaturas_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "valor": {"type": "int", "db_column": "valor", "display_key": "col_valor", "editable": True}}},
    "fsc_tipos": {"display_name_key": "col_fsc", "table": "fsc_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "turnos_tipos": {"display_name_key": "shift_label", "table": "turnos_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "acabamentos_tipos": {"display_name_key": "col_acabamento", "table": "acabamentos_tipos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True}}},
    "equipamentos_tipos": {"display_name_key": "equipment_label","table": "equipamentos_tipos","pk_column": "id",  "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False},       "descricao": {"type": "str", "db_column": "descricao", "display_key": "col_descricao", "editable": True},"tempo_por_folha_ms": {"type": "int","db_column": "tempo_por_folha_ms","display_key": "col_tempo_por_folha", "editable": True}}},
    "equipamento_campos": {"display_name_key": "field_label", "table": "equipamento_campos", "pk_column": "id", "columns": {"id": {"type": "int", "db_column": "id", "display_key": "col_id", "editable": False}, "nome_campo": {"type": "str", "db_column": "nome_campo", "display_key": "col_field_name", "editable": True}, "label_traducao": {"type": "str", "db_column": "label_traducao", "display_key": "col_translation_key", "editable": True}, "tipo_dado": {"type": "str", "db_column": "tipo_dado", "display_key": "col_data_type", "editable": True}, "widget_type": {"type": "str", "db_column": "widget_type", "display_key": "col_widget_type", "editable": True}, "lookup_table": {"type": "str", "db_column": "lookup_table", "display_key": "col_lookup_table", "editable": True}}},
}